#ifndef PCB_OFFSET_ERROR_H
#define PCB_OFFSET_ERROR_H

#include <cstdint>

enum class ERROR_CODE : int32_t {
    SUCCESS = 0,
    ERROR_FILE_NOT_FOUND = -1,
    ERROR_INVALID_PARAMETER = -2,
    ERROR_OUT_OF_MEMORY = -3,
    ERROR_PERMISSION_DENIED = -4,
    ERROR_IO_FAILURE = -5,
    ERROR_TIMEOUT = -6,
    ERROR_UNSUPPORTED_OPERATION = -7,
    ERROR_NETWORK_UNAVAILABLE = -8,
    ERROR_RESOURCE_BUSY = -9,
    ERROR_DATA_CORRUPTION = -10,
    ERROR_OVERFLOW = -11,
    ERROR_UNDERFLOW = -12,
    ERROR_NOT_IMPLEMENTED = -13,
    ERROR_UI_INIT_FAILURE = -14,
    ERROR_UNKNOWN = -100,

    WARNING_DEPRECATED = 1,
    WARNING_UNEXPECTED_BEHAVIOR = 2
};

#endif //PCB_OFFSET_ERROR_H
